import Head from "next/head";

interface IChildren {
  children: React.ReactNode;
}

import { Lato } from "next/font/google";

const lato = Lato({
  subsets: ["latin"],
  weight: "400",

});

// const inter = Inter({ subsets: ["latin"] });

const Layout = ({ children}: IChildren) => {
  return (
    <>
      <Head>
        <title>Lendsqr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <main className={`${lato.className} font-sans `}>    
          {children}
      </main>
    </>
  );
};
export default Layout;
