import Head from "next/head";
import Layout from "@/components/layout/Layout";
import Users from "@/components/dashboard/UserProfile";
import React from "react";
import { Data } from "@/components/dashboard/UserDashboard";
import UserDashboard from "@/components/dashboard/UserDashboard";
import { getUsers } from "../../lib/User";
import styles from "../styles/Main.module.scss"

export async function getStaticProps() {
  const users = await getUsers();
  

  return {
    props: {
      users,
    },
  };
}

const index:React.FC<Data> = ({users}) => {
  
  return (
    <>
      <Head>
        <title>Lendsqr</title>
        <meta name="description" content="Generated by create next app" />

        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <>
     
        <div className={styles.main}>
        <UserDashboard/>  
        <Users users={users}/>
        </div>
        {}
    
      </>
    </>
  );
};

export default index;
