import React from "react";
import Head from "next/head";
import Layout from "@/components/layout/Layout";

const index = () => {
  
  return (
    <>
      <Head>
        <title>Lendsqr</title>
        <meta name="description" content="Generated by create next app" />

        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <Layout>{}</Layout>
    </>
  );
};

export default index;
